### ISSUE TITLE
 Estructura datos servidor aws con peticion 'info'

### ISSUE THREAD

**Issue by rskproductions** [ANTONIOPSD/Alarma_Komobi_Telegram#5]
Se repiten datos a mogollón . Antonio, yo solo se la petición info que es la que nos has proporcionado en tu rutina Python .
Con el sniffer pudistes saber que peticiones hace la app komobi ?

devices:
  settingConfig:
    orientation: 1
    snapToRoad: True
  deviceConfig:
    bleId: XXXXXXXXXXXX
    bleIdActivated: True
    bleIdCode: XXXXXXXX
    calibrationStatus: 3
    certN: 111
    firmwareVersion: 29
    fwType: KMBHW14
    iccId: XXXXXXXXXXXXXXXXX
    imuOffset: 3378,-1344,1512,1,8,47
    index: 1
    mType: 1X
    msisdn: OK
    oGroup: 33
    simProvider: WIRELESS_LOGIC
  deviceStatus:
    alarmSensitivity: 2
    batteryLevel: 7
    batteryValue: 3.96
    calibration: 1
    createdAt: 1671082892
    deviceQuatType: 1
    externalBatteryLevel: 12.45
    externalBatteryLevel6z: 12.45
    isActive: True
    isMuted: False
    lastActivity: 1684608805
    lastMessageType: SERVER_INFO
    lastRoute: 66
    lastSetupDone: False
    lastUse: 1685824249
    numSetups: 1
    parked: True
    readyForCalibratedRoll: False
    readyForCalibratedVertical: False
    stage: 2
    turnedOff: False
    batteryPercentage: 70%
  alarmConfig:
    alarmMode: 1
    alarmType: 2
    areaCenter:
      currentMacBle: XXXXXXXXXXXX
      externalBatteryLevel6z: 12.45
      latitude: 41.39194
      accuracy: 5
      locationType: GPS
      macBle: None
      psiCounterAutoCalib: 0
      speed: 3
      isResent: 1
      autocalibStatus:
        deviceQuatType: 1
        autocalibApplied: False
        autocalibValid: False
      routeId: 66
      phiThetaCounterAutoCalib: 0
      messageType: LAST_MESSAGE
      externalBatteryLevel: 12.7
      installationNumber: 0
      closedBySystem: False
      batteryValue: 4.252
      wifiAccuracyMeters: None
      batteryKeyChain: 3
      wifiLatitude: None
      longitude: 2.123703
      wifiLongitude: None
      timestamp: 1684608805
      batteryLevel: 10
    badAccuracy: False
    isAlarmActive: True
    isFired: False
    lastAlarmPosition:
      currentMacBle: XXXXXXXXXXXX
      externalBatteryLevel6z: 12.45
      latitude: 41.39194
      accuracy: 5
      locationType: GPS
      macBle: None
      psiCounterAutoCalib: 0
      speed: 3
      isResent: 1
      autocalibStatus:
        deviceQuatType: 1
        autocalibApplied: False
        autocalibValid: False
      routeId: 66
      phiThetaCounterAutoCalib: 0
      messageType: LAST_MESSAGE
      externalBatteryLevel: 12.7
      installationNumber: 0
      closedBySystem: False
      batteryValue: 4.252
      wifiAccuracyMeters: None
      batteryKeyChain: 3
      wifiLatitude: None
      longitude: 2.123703
      wifiLongitude: None
      timestamp: 1684608805
      batteryLevel: 10
    lastFired: 1680519472
    notif:
      calls:
        completedCalls: 0
        lastCallId: XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
        lastCallOn: 1680519434
        lastCallStatus: None
        outgoingCalls: 2
      createdOn: 1680519348
      lastAlarmRouteId: 47
      pushes:
        lastPushOn: 1680519421
  subscription:
    callExpirationOn: 1681509600
    expirationOn: 1704495600
    subscriptionTimeMonths: 12
    appType: PRO
    processedExpirationOn: 1704495600
    createdOn: 1672959600
    productType: PRO PREMIUM 1AÑO
    isDeviceConnectivityActive: True
  lastLocations: [{'externalBatteryLevel6z': 12.45, 'latitude': 41.392303, 'accuracy': 7, 'locationType': 'GPS', 'macBle': None, 'psiCounterAutoCalib': 70, 'speed': 0, 'isResent': False, 'autocalibStatus': {'deviceQuatType': 0, 'autocalibApplied': False, 'autocalibValid': False}, 'phiThetaCounterAutoCalib': 511, 'messageType': 'SERVER_INFO', 'externalBatteryLevel': 12.45, 'installationNumber': 0, 'closedBySystem': False, 'batteryValue': 3.96, 'wifiAccuracyMeters': None, 'batteryKeyChain': 0, 'wifiLatitude': None, 'longitude': 2.123806, 'wifiLongitude': None, 'timestamp': 1685824249, 'batteryLevel': 7}]
  name: CLI_ZIRJAN_X
  deviceId: X
  deviceProfile:
    vehicleId: XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
  eCallConfig:
    eCallMode: 1
  lastLocationGoodAccuracy:
    currentMacBle: XXXXXXXXXXXX
    externalBatteryLevel6z: 12.45
    latitude: 41.39194
    accuracy: 5
    locationType: GPS
    macBle: None
    psiCounterAutoCalib: 0
    speed: 3
    isResent: 1
    autocalibStatus:
      deviceQuatType: 1
      autocalibApplied: False
      autocalibValid: False
    routeId: 66
    phiThetaCounterAutoCalib: 0
    messageType: LAST_MESSAGE
    externalBatteryLevel: 12.7
    installationNumber: 0
    closedBySystem: False
    batteryValue: 4.252
    wifiAccuracyMeters: None
    batteryKeyChain: 3
    wifiLatitude: None
    longitude: 2.123703
    wifiLongitude: None
    timestamp: 1684608805
    batteryLevel: 10
  userId: XXXXXX@outlook.es
  activation:
    activated: True
    activatedBy: KOMOBI
    activatedOn: 1673010196
    lastCheck:
      adcBattery: -1
      SMSUp: 1
      charger: 0
      externalBattery: 1291
      adc2Battery: -1
      lastCheckOn: 1673010196
      internalBattery: 4140|10
    result: FINISHED
    validation:
      adcBattery: -1
      SMSUp: 0
      validatedOn: 1673010196
      charger: 0
      externalBattery: 1291
      adc2Battery: 0
      internalBattery: 4140|10
      validate: True
  deviceSetupv40:
    connected: True
    devicePairing: True
    devicePosition: True
    finished: True
    isThereDeviceTimeout: False
    lastMessageOn: 1673013231
    rCalibrating: True
    userAborted: False
    vCalibrating: True
  bleId: XXXXXXXXXXXX
  clientType: B2C

**Comment by ANTONIOPSD** [comment]
Hay más peticiones, se pueden encontrar en el código de la aplicación al desensamblarla.
Por el momento esta repo es solo para obtener la alarma, nada más.


Peticiones que hace la app:

/alarm
/alarm/last
/alarmconfig
/alarms
/commands
/device/mygarage
/device/profile
/device/setup
/device/setup/calibrate
/device/setupv20/calibrate
/device/setupv40
/device/setupv40/step
/device/unpair
/logo
/mutealarm
/route/v2
/routes
/routes/days
/stats/use
/user/contactprofile
/user/contactprofile/locale
/user/notification
/usertoken
/v1/users/{userId}/contactprofile
/v1/users/{userId}/policies/accept?pool=KOMOBI
